// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgx94JwEDI0L2Dwe7pSgmCnN4-tAm7mxs',
    appId: '1:1086695412827:web:506cf3627e52c53128db7e',
    messagingSenderId: '1086695412827',
    projectId: 'flutterfirebase-89305',
    authDomain: 'flutterfirebase-89305.firebaseapp.com',
    storageBucket: 'flutterfirebase-89305.appspot.com',
    measurementId: 'G-0X7ZXSED30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMqqlSLAXkPAEqwcgp3RIRrRuLaxR5_hs',
    appId: '1:1086695412827:android:e91fcdd66bd3d3c928db7e',
    messagingSenderId: '1086695412827',
    projectId: 'flutterfirebase-89305',
    storageBucket: 'flutterfirebase-89305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0WyQ3n2NdJo2j8uKI6s6F6U9u7cpfpYg',
    appId: '1:1086695412827:ios:d99ada282e24269728db7e',
    messagingSenderId: '1086695412827',
    projectId: 'flutterfirebase-89305',
    storageBucket: 'flutterfirebase-89305.appspot.com',
    iosClientId: '1086695412827-ngrjidp8vno7hhltf3f5au8g79ob8ogv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0WyQ3n2NdJo2j8uKI6s6F6U9u7cpfpYg',
    appId: '1:1086695412827:ios:d99ada282e24269728db7e',
    messagingSenderId: '1086695412827',
    projectId: 'flutterfirebase-89305',
    storageBucket: 'flutterfirebase-89305.appspot.com',
    iosClientId: '1086695412827-ngrjidp8vno7hhltf3f5au8g79ob8ogv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgx94JwEDI0L2Dwe7pSgmCnN4-tAm7mxs',
    appId: '1:1086695412827:web:09de0f02eaf0d45628db7e',
    messagingSenderId: '1086695412827',
    projectId: 'flutterfirebase-89305',
    authDomain: 'flutterfirebase-89305.firebaseapp.com',
    storageBucket: 'flutterfirebase-89305.appspot.com',
    measurementId: 'G-X67JHHTWMV',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAgx94JwEDI0L2Dwe7pSgmCnN4-tAm7mxs',
    appId: '1:1086695412827:web:ed00f01671c24c9e28db7e',
    messagingSenderId: '1086695412827',
    projectId: 'flutterfirebase-89305',
    authDomain: 'flutterfirebase-89305.firebaseapp.com',
    storageBucket: 'flutterfirebase-89305.appspot.com',
    measurementId: 'G-CM6SMC3V1P',
  );
}
